version: '4'
services:
  db:
    image: "postgres:latest"
    container_name: db_app
    env_file:
      - .env-non-dev

  redis:
    image: "redis:latest"
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env-non-dev

    container_name: fastapi_app
    command: [ "/fastapi_app/Docker/app.sh" ]

    ports:
      - 9999:8000

    depends_on:
      - db
      - redis
