"""role_id default=1

Revision ID: 9b44dc5b9fbc
Revises: 35dd394e6c5e
Create Date: 2024-02-29 15:01:03.366199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b44dc5b9fbc'
down_revision: Union[str, None] = '35dd394e6c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
